Update service-api.yml for Azure Pipelines

diff --git a/.azure/pipelines/service-api.yml b/.azure/pipelines/service-api.yml
--- a/.azure/pipelines/service-api.yml
+++ b/.azure/pipelines/service-api.yml
@@ -134,14 +134,41 @@ stages:
         command: 'login'
 
     - bash: |
+        set +e
+        deployed=false
         echo "Retrieving service ${SRV} endpoints in namespace ${NS}"
         endpoints=`kubectl -n ${NS} get endpoints ${SRV} --no-headers | awk '{ print \$2 }'`
-        for endpoint in ${endpoints}; do
-          echo "${endpoint}"
+        for host in ${endpoints}; do
+          echo "Checking host:\ ${host}"
+          status_code=`curl -s -o response.txt -w "%{http_code}" "http://${host}/info"`
+          r_body=`cat response.txt`
+          if [ ${status_code} -ne 200 ]; then
+                echo "Request has failed"
+                sleep $timeout
+                continue
+           fi
+
+          s_version=\$(echo \$r_body | jq -r \'.build.version\')
+
+          if [ "\$s_version" = "${version}" ]; then
+                deployed=true
+                break
+           else
+                sleep $timeout
+           fi
         done
+        if \$deployed; then
+            echo "UP"
+            exit 0
+        else
+            echo "Incorrect Server Version"
+            exit 1
+        fi
       displayName: 'Deployment test'
       name: deploymentTest
       env:
         SRV: reportportal-api
         NS: $(namespace)
+        ATTEMPTS: 10
+        VERSION: $(tag)
 
